steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy bengkel \
          --source . \
          --region asia-southeast2 \
          --port 5000 \
          --allow-unauthenticated \
          
timeout: "1600s"

options:
  logging: CLOUD_LOGGING_ONLY